"""Event-driven market-making replay on reconstructed Bybit streams."""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

from p2.research_models import (
    DailyCalibration,
    PnLDecomposition,
    apply_imbalance_skew,
    avellaneda_stoikov_quotes,
    decompose_fills,
    fill_fee,
    glft_quotes,
    symmetric_touch_quotes,
)


StrategyKind = Literal["symmetric", "as", "glft", "glft_imbalance"]
CancellationRule = Literal["cancel-from-back", "proportional", "trades-only"]

# Where a quote sits relative to the reconstructed book at placement time.
#   "displayed"   the price carries displayed size, so we join behind it;
#   "empty_level" the price lies inside the reconstructed window but holds no
#                 displayed size, so we stand alone at the front of it;
#   "beyond_book" the price lies deeper than the deepest reconstructed level, so
#                 the queue ahead is unknown and no fill may be claimed.
PlacementState = Literal["displayed", "empty_level", "beyond_book"]


@dataclass(frozen=True)
class StrategySpec:
    """One preregistered quoting configuration."""

    kind: StrategyKind
    gamma: float | None = None
    beta: float | None = None

    @property
    def name(self) -> str:
        if self.kind == "symmetric":
            return "symmetric"
        if self.kind == "as":
            return f"as_gamma_{self.gamma:g}"
        if self.kind == "glft":
            return f"glft_gamma_{self.gamma:g}"
        return f"glft_imbalance_gamma_{self.gamma:g}_beta_{self.beta:g}"


@dataclass(frozen=True)
class ReplaySettings:
    """Execution settings fixed before a daily replay."""

    order_size: float = 0.01
    tick_size: float = 0.1
    requote_ms: int = 100
    inventory_limit: float = 0.05
    maker_fee_rate: float = 0.0002
    taker_fee_rate: float = 0.00055
    latency_ms: int = 50
    cancellation_rule: CancellationRule = "proportional"

    def __post_init__(self) -> None:
        if min(self.order_size, self.tick_size, self.requote_ms, self.inventory_limit) <= 0:
            raise ValueError("sizes, tick, requote interval, and inventory limit must be positive")
        if self.latency_ms < 0:
            raise ValueError("latency_ms must be nonnegative")
        if self.cancellation_rule not in {
            "cancel-from-back",
            "proportional",
            "trades-only",
        }:
            raise ValueError("unsupported cancellation rule")


@dataclass(frozen=True)
class CryptoFill:
    """One passive fill generated by the replay."""

    time_ms: int
    side: Literal["bid", "ask"]
    price: float
    size: float
    midpoint: float
    fee: float

    @property
    def inventory_change(self) -> float:
        return self.size if self.side == "bid" else -self.size


@dataclass(frozen=True)
class DailyReplayResult:
    """Numeric outputs from one strategy and symbol-day."""

    symbol: str
    date: str
    strategy: str
    fills: tuple[CryptoFill, ...]
    quote_count: int
    quote_volume: float
    empty_level_placements: int
    beyond_book_placements: int
    gross_pnl: float
    fees: float
    net_pnl: float
    end_inventory: float
    mean_abs_inventory: float
    inventory_std: float
    max_abs_inventory: float
    final_midpoint: float
    decomposition: PnLDecomposition
    markouts: dict[int, tuple[float, ...]]

    @property
    def fill_count(self) -> int:
        return len(self.fills)

    @property
    def filled_volume(self) -> float:
        return float(sum(fill.size for fill in self.fills))

    @property
    def fill_ratio(self) -> float:
        return self.filled_volume / self.quote_volume if self.quote_volume else 0.0

    @property
    def quote_to_fill(self) -> float:
        return self.quote_count / self.fill_count if self.fill_count else np.inf


@dataclass(slots=True)
class _WorkingOrder:
    side: Literal["bid", "ask"]
    price: float
    remaining: float
    ahead: float
    market_size: float
    placement: PlacementState

    @property
    def fillable(self) -> bool:
        """True when the queue at this price is modelled rather than unknown."""
        return self.placement != "beyond_book"


@dataclass(frozen=True, slots=True)
class _QuoteCommand:
    effective_ms: int
    bid: float | None
    ask: float | None


@dataclass(frozen=True)
class BybitEventArrays:
    """Columnar event data reusable across multiple strategy replays."""

    times: np.ndarray
    is_book: np.ndarray
    book_times: np.ndarray
    book_valid: np.ndarray
    best_bids: np.ndarray
    best_bid_sizes: np.ndarray
    best_asks: np.ndarray
    best_ask_sizes: np.ndarray
    bid_offsets: np.ndarray
    bid_prices: np.ndarray
    bid_sizes: np.ndarray
    ask_offsets: np.ndarray
    ask_prices: np.ndarray
    ask_sizes: np.ndarray
    trade_times: np.ndarray
    trade_prices: np.ndarray
    trade_volumes: np.ndarray
    trade_sides: np.ndarray


def _list_storage(column: pa.ChunkedArray) -> tuple[np.ndarray, np.ndarray]:
    values = column.combine_chunks()
    return (
        values.offsets.to_numpy(zero_copy_only=False).astype(np.int64),
        values.values.to_numpy(zero_copy_only=False).astype(np.float64),
    )


def load_bybit_events(source: str | Path) -> BybitEventArrays:
    """Load one reconstructed stream into reusable columnar arrays."""
    table = pq.read_table(
        Path(source),
        columns=[
            "time",
            "event_type",
            "book_valid",
            "best_bid",
            "best_bid_size",
            "best_ask",
            "best_ask_size",
            "bid_prices",
            "bid_sizes",
            "ask_prices",
            "ask_sizes",
            "trade_price",
            "trade_volume",
            "trade_side",
        ],
    )
    times = table["time"].to_numpy(zero_copy_only=False)
    times = times.astype("datetime64[ms]").astype(np.int64)
    is_book = pc.equal(table["event_type"], "book").to_numpy(zero_copy_only=False)
    book = table.filter(pa.array(is_book))
    trade = table.filter(pa.array(~is_book))
    book_times = book["time"].to_numpy(zero_copy_only=False)
    book_times = book_times.astype("datetime64[ms]").astype(np.int64)
    trade_times = trade["time"].to_numpy(zero_copy_only=False)
    trade_times = trade_times.astype("datetime64[ms]").astype(np.int64)
    bid_offsets, bid_prices = _list_storage(book["bid_prices"])
    _, bid_sizes = _list_storage(book["bid_sizes"])
    ask_offsets, ask_prices = _list_storage(book["ask_prices"])
    _, ask_sizes = _list_storage(book["ask_sizes"])
    return BybitEventArrays(
        times=times,
        is_book=is_book,
        book_times=book_times,
        book_valid=book["book_valid"].to_numpy(zero_copy_only=False).astype(bool),
        best_bids=book["best_bid"].to_numpy(zero_copy_only=False).astype(np.float64),
        best_bid_sizes=book["best_bid_size"].to_numpy(zero_copy_only=False).astype(np.float64),
        best_asks=book["best_ask"].to_numpy(zero_copy_only=False).astype(np.float64),
        best_ask_sizes=book["best_ask_size"].to_numpy(zero_copy_only=False).astype(np.float64),
        bid_offsets=bid_offsets,
        bid_prices=bid_prices,
        bid_sizes=bid_sizes,
        ask_offsets=ask_offsets,
        ask_prices=ask_prices,
        ask_sizes=ask_sizes,
        trade_times=trade_times,
        trade_prices=trade["trade_price"].to_numpy(zero_copy_only=False).astype(np.float64),
        trade_volumes=trade["trade_volume"].to_numpy(zero_copy_only=False).astype(np.float64),
        trade_sides=np.asarray(trade["trade_side"].to_pylist(), dtype=object),
    )


def _level_slice(offsets: np.ndarray, values: np.ndarray, row: int) -> np.ndarray:
    return values[offsets[row] : offsets[row + 1]]


def _depth_at_price(
    prices: np.ndarray,
    sizes: np.ndarray,
    price: float,
    tick_size: float,
) -> float | None:
    matches = np.flatnonzero(np.abs(prices - price) <= tick_size * 1e-6)
    if len(matches) == 0:
        return None
    return float(sizes[matches[0]])


def _round_bid(price: float, tick_size: float) -> float:
    return float(np.floor(price / tick_size + 1e-9) * tick_size)


def _round_ask(price: float, tick_size: float) -> float:
    return float(np.ceil(price / tick_size - 1e-9) * tick_size)


def _strategy_quotes(
    spec: StrategySpec,
    calibration: DailyCalibration,
    *,
    best_bid: float,
    best_ask: float,
    best_bid_size: float,
    best_ask_size: float,
    inventory: float,
    elapsed_seconds: float,
    settings: ReplaySettings,
) -> tuple[float, float]:
    if spec.kind == "symmetric":
        return symmetric_touch_quotes(best_bid, best_ask)
    if spec.gamma is None:
        raise ValueError("gamma is required for this strategy")
    midpoint = 0.5 * (best_bid + best_ask)
    if spec.kind == "as":
        return avellaneda_stoikov_quotes(
            midpoint,
            inventory,
            elapsed_seconds,
            gamma=spec.gamma,
            sigma=calibration.sigma,
            kappa=calibration.kappa,
        )
    bid, ask = glft_quotes(
        midpoint,
        inventory,
        gamma=spec.gamma,
        sigma=calibration.sigma,
        A=calibration.A,
        kappa=calibration.kappa,
        order_size=settings.order_size,
    )
    if spec.kind == "glft_imbalance":
        if spec.beta is None:
            raise ValueError("beta is required for imbalance quoting")
        total_touch = best_bid_size + best_ask_size
        imbalance = (best_bid_size - best_ask_size) / total_touch if total_touch > 0.0 else 0.0
        bid, ask = apply_imbalance_skew(
            bid,
            ask,
            imbalance,
            beta=spec.beta,
            tick_size=settings.tick_size,
        )
    return bid, ask


def _update_queue(
    order: _WorkingOrder | None,
    prices: np.ndarray,
    sizes: np.ndarray,
    settings: ReplaySettings,
) -> None:
    if order is None:
        return
    new_size = _depth_at_price(prices, sizes, order.price, settings.tick_size)
    if new_size is None:
        # No displayed size at our price. Inside the reconstructed window that
        # means the level is empty and we stand alone at its front. Deeper than
        # the window it only means the price drifted out of view, so an order
        # that already holds a modelled position keeps it unchanged.
        if _classify_placement(order.side, order.price, prices) == "empty_level":
            order.ahead = 0.0
            order.market_size = 0.0
            order.placement = "empty_level"
        return
    if order.placement == "beyond_book":
        # First sight of this price: join behind everything displayed there.
        order.ahead = new_size
        order.market_size = new_size
        order.placement = "displayed"
        return
    # Traded volume is charged to the queue when the trade is processed, so any
    # size lost between book snapshots is cancellation. "trades-only" grants no
    # credit for it, which is the assumption the external engine's risk-adverse
    # queue model makes and the reference point for the cross-check.
    reduction = max(order.market_size - new_size, 0.0)
    if reduction > 0.0 and order.ahead > 0.0:
        if settings.cancellation_rule == "cancel-from-back":
            behind = max(order.market_size - order.ahead, 0.0)
            order.ahead = max(order.ahead - max(reduction - behind, 0.0), 0.0)
        elif settings.cancellation_rule == "proportional" and order.market_size > 0.0:
            order.ahead *= max(1.0 - reduction / order.market_size, 0.0)
    order.market_size = new_size


def _classify_placement(
    side: Literal["bid", "ask"],
    price: float,
    prices: np.ndarray,
) -> PlacementState:
    """Say whether a price without displayed size is empty or simply unseen.

    The reconstruction keeps only the top levels of each side, so a quote price
    absent from that window means one of two very different things. Inside the
    window the book genuinely shows no size at that tick and a resting order
    stands alone at the front of it. Deeper than the window we know nothing
    about the queue, and claiming a position there would invent liquidity.
    """
    finite = prices[np.isfinite(prices)]
    if finite.size == 0:
        return "beyond_book"
    if side == "bid":
        return "empty_level" if price >= float(finite.min()) else "beyond_book"
    return "empty_level" if price <= float(finite.max()) else "beyond_book"


def _new_working_order(
    side: Literal["bid", "ask"],
    price: float,
    prices: np.ndarray,
    sizes: np.ndarray,
    settings: ReplaySettings,
) -> _WorkingOrder:
    depth = _depth_at_price(prices, sizes, price, settings.tick_size)
    if depth is not None:
        placement: PlacementState = "displayed"
        initial_depth = float(depth)
    else:
        placement = _classify_placement(side, price, prices)
        initial_depth = 0.0
    return _WorkingOrder(
        side=side,
        price=price,
        remaining=settings.order_size,
        ahead=initial_depth,
        market_size=initial_depth,
        placement=placement,
    )


def _inventory_samples(fills: list[CryptoFill], start_ms: int, end_ms: int) -> np.ndarray:
    seconds = np.arange(start_ms // 1_000, end_ms // 1_000 + 1, dtype=np.int64)
    if not fills:
        return np.zeros(len(seconds), dtype=np.float64)
    fill_times = np.asarray([fill.time_ms for fill in fills], dtype=np.int64)
    changes = np.asarray([fill.inventory_change for fill in fills], dtype=np.float64)
    cumulative = np.cumsum(changes)
    positions = np.searchsorted(fill_times, seconds * 1_000 + 999, side="right") - 1
    samples = np.zeros(len(seconds), dtype=np.float64)
    available = positions >= 0
    samples[available] = cumulative[positions[available]]
    return samples


def _fill_markouts(
    fills: list[CryptoFill],
    book_times: np.ndarray,
    book_valid: np.ndarray,
    best_bids: np.ndarray,
    best_asks: np.ndarray,
) -> dict[int, tuple[float, ...]]:
    horizons = (1, 5, 30, 60)
    output: dict[int, list[float]] = {horizon: [] for horizon in horizons}
    for fill in fills:
        direction = 1.0 if fill.side == "bid" else -1.0
        for horizon in horizons:
            position = np.searchsorted(
                book_times, fill.time_ms + horizon * 1_000, side="right"
            ) - 1
            if position < 0 or position >= len(book_times) or not book_valid[position]:
                continue
            future_mid = 0.5 * (best_bids[position] + best_asks[position])
            output[horizon].append(direction * fill.size * (future_mid - fill.midpoint))
    return {horizon: tuple(values) for horizon, values in output.items()}


def replay_bybit_day(
    source: str | Path | BybitEventArrays,
    *,
    symbol: str,
    date: str,
    strategy: StrategySpec,
    calibration: DailyCalibration,
    settings: ReplaySettings = ReplaySettings(),
) -> DailyReplayResult:
    """Replay one reconstructed symbol-day with delayed queue-aware quotes."""
    events = source if isinstance(source, BybitEventArrays) else load_bybit_events(source)
    if len(events.times) == 0 or len(events.book_times) == 0:
        raise ValueError("event stream is empty")
    if np.any(np.diff(events.times) < 0):
        raise ValueError("event stream times must be nondecreasing")

    commands: deque[_QuoteCommand] = deque()
    bid_order: _WorkingOrder | None = None
    ask_order: _WorkingOrder | None = None
    current_valid = False
    best_bid = np.nan
    best_bid_size = np.nan
    best_ask = np.nan
    best_ask_size = np.nan
    bid_prices = np.empty(0, dtype=np.float64)
    bid_sizes = np.empty(0, dtype=np.float64)
    ask_prices = np.empty(0, dtype=np.float64)
    ask_sizes = np.empty(0, dtype=np.float64)
    inventory = 0.0
    max_abs_inventory = 0.0
    cash = 0.0
    quote_count = 0
    quote_volume = 0.0
    empty_level_placements = 0
    beyond_book_placements = 0
    fills: list[CryptoFill] = []
    last_decision_ms = -10**18
    submitted_bid: float | None = None
    submitted_ask: float | None = None
    book_row = 0
    trade_row = 0
    session_start_ms = int(events.times[0])

    def activate_due(now_ms: int) -> None:
        nonlocal bid_order, ask_order, quote_count, quote_volume
        nonlocal empty_level_placements, beyond_book_placements
        while commands and commands[0].effective_ms <= now_ms:
            command = commands.popleft()
            target_bid = command.bid
            target_ask = command.ask
            if not current_valid:
                bid_order = None
                ask_order = None
                continue
            if inventory + settings.order_size > settings.inventory_limit + 1e-12:
                target_bid = None
            if inventory - settings.order_size < -settings.inventory_limit - 1e-12:
                target_ask = None
            if target_bid is not None and target_bid >= best_ask:
                target_bid = _round_bid(best_ask - settings.tick_size, settings.tick_size)
            if target_ask is not None and target_ask <= best_bid:
                target_ask = _round_ask(best_bid + settings.tick_size, settings.tick_size)
            if target_bid is None:
                bid_order = None
            elif bid_order is None or bid_order.price != target_bid:
                bid_order = _new_working_order(
                    "bid", target_bid, bid_prices, bid_sizes, settings
                )
                quote_count += 1
                quote_volume += settings.order_size
                empty_level_placements += bid_order.placement == "empty_level"
                beyond_book_placements += bid_order.placement == "beyond_book"
            if target_ask is None:
                ask_order = None
            elif ask_order is None or ask_order.price != target_ask:
                ask_order = _new_working_order(
                    "ask", target_ask, ask_prices, ask_sizes, settings
                )
                quote_count += 1
                quote_volume += settings.order_size
                empty_level_placements += ask_order.placement == "empty_level"
                beyond_book_placements += ask_order.placement == "beyond_book"

    for event_row, now_ms in enumerate(events.times):
        now_ms = int(now_ms)
        activate_due(now_ms)
        if events.is_book[event_row]:
            current_valid = bool(events.book_valid[book_row])
            if current_valid:
                new_bid_prices = _level_slice(
                    events.bid_offsets, events.bid_prices, book_row
                )
                new_bid_sizes = _level_slice(events.bid_offsets, events.bid_sizes, book_row)
                new_ask_prices = _level_slice(
                    events.ask_offsets, events.ask_prices, book_row
                )
                new_ask_sizes = _level_slice(events.ask_offsets, events.ask_sizes, book_row)
                _update_queue(bid_order, new_bid_prices, new_bid_sizes, settings)
                _update_queue(ask_order, new_ask_prices, new_ask_sizes, settings)
                best_bid = float(events.best_bids[book_row])
                best_bid_size = float(events.best_bid_sizes[book_row])
                best_ask = float(events.best_asks[book_row])
                best_ask_size = float(events.best_ask_sizes[book_row])
                bid_prices, bid_sizes = new_bid_prices, new_bid_sizes
                ask_prices, ask_sizes = new_ask_prices, new_ask_sizes
            else:
                bid_order = None
                ask_order = None
                commands.clear()
                submitted_bid = None
                submitted_ask = None
            book_row += 1
        else:
            trade_side = str(events.trade_sides[trade_row]).lower()
            trade_price = float(events.trade_prices[trade_row])
            trade_volume = float(events.trade_volumes[trade_row])
            if trade_side == "sell":
                order = bid_order
            elif trade_side == "buy":
                order = ask_order
            else:
                raise ValueError(f"unsupported aggressor side: {trade_side}")
            if current_valid and order is not None and order.fillable:
                tolerance = settings.tick_size * 1e-6
                at_price = abs(order.price - trade_price) <= tolerance
                swept_through = (
                    order.side == "bid" and trade_price < order.price - tolerance
                ) or (order.side == "ask" and trade_price > order.price + tolerance)
                available = 0.0
                if at_price or swept_through:
                    # Bybit prints one row per matched price level, so aggressor
                    # volume is observed level by level. Whether the row lands on
                    # our price or past it, it can only reach us after clearing
                    # the queue ahead, and it can only fill what it actually
                    # traded. A sweep still fills us completely, but through its
                    # own volume rather than by fiat.
                    consumed_ahead = min(order.ahead, trade_volume)
                    order.ahead -= consumed_ahead
                    available = max(trade_volume - consumed_ahead, 0.0)
                    if swept_through:
                        order.market_size = 0.0
                    else:
                        order.market_size = max(order.market_size - trade_volume, 0.0)
                capacity = (
                    settings.inventory_limit - inventory
                    if order.side == "bid"
                    else settings.inventory_limit + inventory
                )
                fill_size = min(order.remaining, available, max(capacity, 0.0))
                if fill_size > 1e-12:
                    midpoint = 0.5 * (best_bid + best_ask)
                    fee = fill_fee(order.price, fill_size, settings.maker_fee_rate)
                    fill = CryptoFill(
                        time_ms=now_ms,
                        side=order.side,
                        price=order.price,
                        size=fill_size,
                        midpoint=midpoint,
                        fee=fee,
                    )
                    fills.append(fill)
                    inventory += fill.inventory_change
                    cash -= fill.inventory_change * fill.price + fee
                    max_abs_inventory = max(max_abs_inventory, abs(inventory))
                    order.remaining -= fill_size
                    if order.remaining <= 1e-12:
                        if order.side == "bid":
                            bid_order = None
                            submitted_bid = None
                        else:
                            ask_order = None
                            submitted_ask = None
                    elif capacity - fill_size <= 1e-12:
                        if order.side == "bid":
                            bid_order = None
                            submitted_bid = None
                        else:
                            ask_order = None
                            submitted_ask = None
            trade_row += 1

        if current_valid and now_ms - last_decision_ms >= settings.requote_ms:
            raw_bid, raw_ask = _strategy_quotes(
                strategy,
                calibration,
                best_bid=best_bid,
                best_ask=best_ask,
                best_bid_size=best_bid_size,
                best_ask_size=best_ask_size,
                inventory=inventory,
                elapsed_seconds=(now_ms - session_start_ms) / 1_000.0,
                settings=settings,
            )
            target_bid = _round_bid(raw_bid, settings.tick_size)
            target_ask = _round_ask(raw_ask, settings.tick_size)
            if inventory + settings.order_size > settings.inventory_limit + 1e-12:
                target_bid = None
            if inventory - settings.order_size < -settings.inventory_limit - 1e-12:
                target_ask = None
            if target_bid != submitted_bid or target_ask != submitted_ask:
                commands.append(
                    _QuoteCommand(
                        effective_ms=now_ms + settings.latency_ms,
                        bid=target_bid,
                        ask=target_ask,
                    )
                )
                submitted_bid, submitted_ask = target_bid, target_ask
            last_decision_ms = now_ms
            if settings.latency_ms == 0:
                activate_due(now_ms)

    valid_rows = np.flatnonzero(events.book_valid)
    if len(valid_rows) == 0:
        raise ValueError("event stream has no valid closing midpoint")
    final_row = int(valid_rows[-1])
    final_midpoint = 0.5 * (
        events.best_bids[final_row] + events.best_asks[final_row]
    )
    changes = [fill.inventory_change for fill in fills]
    decomposition = decompose_fills(
        changes,
        [fill.price for fill in fills],
        [fill.midpoint for fill in fills],
        [settings.maker_fee_rate] * len(fills),
        final_midpoint=final_midpoint,
    )
    inventory_samples = _inventory_samples(
        fills, int(events.times[0]), int(events.times[-1])
    )
    fees = float(sum(fill.fee for fill in fills))
    gross_pnl = decomposition.realized_spread + decomposition.inventory_revaluation
    net_pnl = cash + inventory * final_midpoint
    if not np.isclose(net_pnl, decomposition.net_pnl, atol=1e-9):
        raise RuntimeError("fill accounting does not reconcile")
    return DailyReplayResult(
        symbol=symbol,
        date=date,
        strategy=strategy.name,
        fills=tuple(fills),
        quote_count=quote_count,
        quote_volume=quote_volume,
        empty_level_placements=empty_level_placements,
        beyond_book_placements=beyond_book_placements,
        gross_pnl=float(gross_pnl),
        fees=fees,
        net_pnl=float(net_pnl),
        end_inventory=float(inventory),
        mean_abs_inventory=float(np.mean(np.abs(inventory_samples))),
        inventory_std=float(np.std(inventory_samples)),
        max_abs_inventory=float(max_abs_inventory),
        final_midpoint=float(final_midpoint),
        decomposition=decomposition,
        markouts=_fill_markouts(
            fills,
            events.book_times,
            events.book_valid,
            events.best_bids,
            events.best_asks,
        ),
    )
